### ISSUE TITLE
Add `struct SingletonPortgraph` containing a single node.

### ISSUE THREAD

**Issue by doug-q** [CQCL/portgraph#154]
In https://github.com/CQCL/hugr/issues/1652 we found that constructing single-node-`SiblingSubgraph`s is very expensive, requiring iteration over all nodes in the parent graph.

If we had a 
```
struct SingletonSubgraph{ ...}

impl SingletonSubgraph{ 
  pub fn new(g: &impl PortView, node: Node) -> Self { ... }
} 
```

We could, in the single node case, construct a `SingletonSubgraph` and work with that rather than using `portgraph::views::subgraph`.

**Comment by aborgna-q** [comment]
The optimizations in #157 should remove the need for an specialized singleton structure.
